version: '3.1'

services:
  db:
    image: mariadb:10.3
    restart: always
    container_name: mariadb
    environment:
#      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
    volumes:
      - /var/run/mysqld:/var/run/mysqld
      - datos:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1

volumes:
   datos:
