version: '3.1'

services:
  db:
    image: mysql
    restart: always
    container_name: mysql_db
    hostname: mysqlhost
    environment:
#      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
    volumes:
      - /var/run/mysqld:/var/run/mysqld
      - datos:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: mysql_phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1

volumes:
   datos:
