version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongodb-express
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://user:pass@mongo:27017/


volumes:
  data:


# CONEXIÓN LOCAL:
# info: https://www.mongodb.com/docs/manual/reference/connection-string-options/#authentication-options
# docker exec -it mongodb mongosh "mongodb://user:pass@127.0.0.1:27017/payload?authSource=admin"


# MONGODB ATLAS:
# docker exec -it mongodb mongosh "mongodb+srv://jose:password@cluster0.hhmhj.mongodb.net/payload?retryWrites=true&w=majority&appName=Cluster0"
